spring:
  application:
    name: base-data
  datasource:
        name: test
        url: jdbc:postgresql://192.168.0.250:5432/hnvmns6000
        username: postgres
        password: hngd5618
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: org.postgresql.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
        
mybatis:
  mapper-locations: 
    - /com/hngd/mapping/*.xml
  type-aliases-package: com.hngd.model 
server:
  port: 8084
eureka:
  client:
    service-url:
      defaultZone: http://192.168.0.141:12330/eureka,http://192.168.0.142:12330/eureka