package com.hngd.model;

public class DictDetailInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_dict_detail.id
     *
     * @mbggenerated Wed Sep 12 17:11:40 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_dict_detail.detail_code
     *
     * @mbggenerated Wed Sep 12 17:11:40 CST 2018
     */
    private String detailCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_dict_detail.detail_value
     *
     * @mbggenerated Wed Sep 12 17:11:40 CST 2018
     */
    private String detailValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_dict_detail.remark
     *
     * @mbggenerated Wed Sep 12 17:11:40 CST 2018
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_dict_detail.isusedstate
     *
     * @mbggenerated Wed Sep 12 17:11:40 CST 2018
     */
    private Short isusedstate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_dict_detail.dict_code
     *
     * @mbggenerated Wed Sep 12 17:11:40 CST 2018
     */
    private String dictCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_dict_detail.dict_name
     *
     * @mbggenerated Wed Sep 12 17:11:40 CST 2018
     */
    private String dictName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_dict_detail.flag
     *
     * @mbggenerated Wed Sep 12 17:11:40 CST 2018
     */
    private String flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_dict_detail.dict_parent_code
     *
     * @mbggenerated Wed Sep 12 17:11:40 CST 2018
     */
    private String dictParentCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_dict_detail.id
     *
     * @return the value of vw_dict_detail.id
     *
     * @mbggenerated Wed Sep 12 17:11:40 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_dict_detail.id
     *
     * @param id the value for vw_dict_detail.id
     *
     * @mbggenerated Wed Sep 12 17:11:40 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_dict_detail.detail_code
     *
     * @return the value of vw_dict_detail.detail_code
     *
     * @mbggenerated Wed Sep 12 17:11:40 CST 2018
     */
    public String getDetailCode() {
        return detailCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_dict_detail.detail_code
     *
     * @param detailCode the value for vw_dict_detail.detail_code
     *
     * @mbggenerated Wed Sep 12 17:11:40 CST 2018
     */
    public void setDetailCode(String detailCode) {
        this.detailCode = detailCode == null ? null : detailCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_dict_detail.detail_value
     *
     * @return the value of vw_dict_detail.detail_value
     *
     * @mbggenerated Wed Sep 12 17:11:40 CST 2018
     */
    public String getDetailValue() {
        return detailValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_dict_detail.detail_value
     *
     * @param detailValue the value for vw_dict_detail.detail_value
     *
     * @mbggenerated Wed Sep 12 17:11:40 CST 2018
     */
    public void setDetailValue(String detailValue) {
        this.detailValue = detailValue == null ? null : detailValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_dict_detail.remark
     *
     * @return the value of vw_dict_detail.remark
     *
     * @mbggenerated Wed Sep 12 17:11:40 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_dict_detail.remark
     *
     * @param remark the value for vw_dict_detail.remark
     *
     * @mbggenerated Wed Sep 12 17:11:40 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_dict_detail.isusedstate
     *
     * @return the value of vw_dict_detail.isusedstate
     *
     * @mbggenerated Wed Sep 12 17:11:40 CST 2018
     */
    public Short getIsusedstate() {
        return isusedstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_dict_detail.isusedstate
     *
     * @param isusedstate the value for vw_dict_detail.isusedstate
     *
     * @mbggenerated Wed Sep 12 17:11:40 CST 2018
     */
    public void setIsusedstate(Short isusedstate) {
        this.isusedstate = isusedstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_dict_detail.dict_code
     *
     * @return the value of vw_dict_detail.dict_code
     *
     * @mbggenerated Wed Sep 12 17:11:40 CST 2018
     */
    public String getDictCode() {
        return dictCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_dict_detail.dict_code
     *
     * @param dictCode the value for vw_dict_detail.dict_code
     *
     * @mbggenerated Wed Sep 12 17:11:40 CST 2018
     */
    public void setDictCode(String dictCode) {
        this.dictCode = dictCode == null ? null : dictCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_dict_detail.dict_name
     *
     * @return the value of vw_dict_detail.dict_name
     *
     * @mbggenerated Wed Sep 12 17:11:40 CST 2018
     */
    public String getDictName() {
        return dictName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_dict_detail.dict_name
     *
     * @param dictName the value for vw_dict_detail.dict_name
     *
     * @mbggenerated Wed Sep 12 17:11:40 CST 2018
     */
    public void setDictName(String dictName) {
        this.dictName = dictName == null ? null : dictName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_dict_detail.flag
     *
     * @return the value of vw_dict_detail.flag
     *
     * @mbggenerated Wed Sep 12 17:11:40 CST 2018
     */
    public String getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_dict_detail.flag
     *
     * @param flag the value for vw_dict_detail.flag
     *
     * @mbggenerated Wed Sep 12 17:11:40 CST 2018
     */
    public void setFlag(String flag) {
        this.flag = flag == null ? null : flag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_dict_detail.dict_parent_code
     *
     * @return the value of vw_dict_detail.dict_parent_code
     *
     * @mbggenerated Wed Sep 12 17:11:40 CST 2018
     */
    public String getDictParentCode() {
        return dictParentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_dict_detail.dict_parent_code
     *
     * @param dictParentCode the value for vw_dict_detail.dict_parent_code
     *
     * @mbggenerated Wed Sep 12 17:11:40 CST 2018
     */
    public void setDictParentCode(String dictParentCode) {
        this.dictParentCode = dictParentCode == null ? null : dictParentCode.trim();
    }
}