package com.hngd.model;

import java.util.ArrayList;
import java.util.List;

public class DictDetailExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_dict_detail
     *
     * @mbggenerated Wed Sep 12 17:11:40 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_dict_detail
     *
     * @mbggenerated Wed Sep 12 17:11:40 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_dict_detail
     *
     * @mbggenerated Wed Sep 12 17:11:40 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dict_detail
     *
     * @mbggenerated Wed Sep 12 17:11:40 CST 2018
     */
    public DictDetailExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dict_detail
     *
     * @mbggenerated Wed Sep 12 17:11:40 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dict_detail
     *
     * @mbggenerated Wed Sep 12 17:11:40 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dict_detail
     *
     * @mbggenerated Wed Sep 12 17:11:40 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dict_detail
     *
     * @mbggenerated Wed Sep 12 17:11:40 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dict_detail
     *
     * @mbggenerated Wed Sep 12 17:11:40 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dict_detail
     *
     * @mbggenerated Wed Sep 12 17:11:40 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dict_detail
     *
     * @mbggenerated Wed Sep 12 17:11:40 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dict_detail
     *
     * @mbggenerated Wed Sep 12 17:11:40 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dict_detail
     *
     * @mbggenerated Wed Sep 12 17:11:40 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dict_detail
     *
     * @mbggenerated Wed Sep 12 17:11:40 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_dict_detail
     *
     * @mbggenerated Wed Sep 12 17:11:40 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andDictCodeIsNull() {
            addCriterion("dict_code is null");
            return (Criteria) this;
        }

        public Criteria andDictCodeIsNotNull() {
            addCriterion("dict_code is not null");
            return (Criteria) this;
        }

        public Criteria andDictCodeEqualTo(String value) {
            addCriterion("dict_code =", value, "dictCode");
            return (Criteria) this;
        }

        public Criteria andDictCodeNotEqualTo(String value) {
            addCriterion("dict_code <>", value, "dictCode");
            return (Criteria) this;
        }

        public Criteria andDictCodeGreaterThan(String value) {
            addCriterion("dict_code >", value, "dictCode");
            return (Criteria) this;
        }

        public Criteria andDictCodeGreaterThanOrEqualTo(String value) {
            addCriterion("dict_code >=", value, "dictCode");
            return (Criteria) this;
        }

        public Criteria andDictCodeLessThan(String value) {
            addCriterion("dict_code <", value, "dictCode");
            return (Criteria) this;
        }

        public Criteria andDictCodeLessThanOrEqualTo(String value) {
            addCriterion("dict_code <=", value, "dictCode");
            return (Criteria) this;
        }

        public Criteria andDictCodeLike(String value) {
            addCriterion("dict_code like", value, "dictCode");
            return (Criteria) this;
        }

        public Criteria andDictCodeNotLike(String value) {
            addCriterion("dict_code not like", value, "dictCode");
            return (Criteria) this;
        }

        public Criteria andDictCodeIn(List<String> values) {
            addCriterion("dict_code in", values, "dictCode");
            return (Criteria) this;
        }

        public Criteria andDictCodeNotIn(List<String> values) {
            addCriterion("dict_code not in", values, "dictCode");
            return (Criteria) this;
        }

        public Criteria andDictCodeBetween(String value1, String value2) {
            addCriterion("dict_code between", value1, value2, "dictCode");
            return (Criteria) this;
        }

        public Criteria andDictCodeNotBetween(String value1, String value2) {
            addCriterion("dict_code not between", value1, value2, "dictCode");
            return (Criteria) this;
        }

        public Criteria andDetailCodeIsNull() {
            addCriterion("detail_code is null");
            return (Criteria) this;
        }

        public Criteria andDetailCodeIsNotNull() {
            addCriterion("detail_code is not null");
            return (Criteria) this;
        }

        public Criteria andDetailCodeEqualTo(String value) {
            addCriterion("detail_code =", value, "detailCode");
            return (Criteria) this;
        }

        public Criteria andDetailCodeNotEqualTo(String value) {
            addCriterion("detail_code <>", value, "detailCode");
            return (Criteria) this;
        }

        public Criteria andDetailCodeGreaterThan(String value) {
            addCriterion("detail_code >", value, "detailCode");
            return (Criteria) this;
        }

        public Criteria andDetailCodeGreaterThanOrEqualTo(String value) {
            addCriterion("detail_code >=", value, "detailCode");
            return (Criteria) this;
        }

        public Criteria andDetailCodeLessThan(String value) {
            addCriterion("detail_code <", value, "detailCode");
            return (Criteria) this;
        }

        public Criteria andDetailCodeLessThanOrEqualTo(String value) {
            addCriterion("detail_code <=", value, "detailCode");
            return (Criteria) this;
        }

        public Criteria andDetailCodeLike(String value) {
            addCriterion("detail_code like", value, "detailCode");
            return (Criteria) this;
        }

        public Criteria andDetailCodeNotLike(String value) {
            addCriterion("detail_code not like", value, "detailCode");
            return (Criteria) this;
        }

        public Criteria andDetailCodeIn(List<String> values) {
            addCriterion("detail_code in", values, "detailCode");
            return (Criteria) this;
        }

        public Criteria andDetailCodeNotIn(List<String> values) {
            addCriterion("detail_code not in", values, "detailCode");
            return (Criteria) this;
        }

        public Criteria andDetailCodeBetween(String value1, String value2) {
            addCriterion("detail_code between", value1, value2, "detailCode");
            return (Criteria) this;
        }

        public Criteria andDetailCodeNotBetween(String value1, String value2) {
            addCriterion("detail_code not between", value1, value2, "detailCode");
            return (Criteria) this;
        }

        public Criteria andDetailValueIsNull() {
            addCriterion("detail_value is null");
            return (Criteria) this;
        }

        public Criteria andDetailValueIsNotNull() {
            addCriterion("detail_value is not null");
            return (Criteria) this;
        }

        public Criteria andDetailValueEqualTo(String value) {
            addCriterion("detail_value =", value, "detailValue");
            return (Criteria) this;
        }

        public Criteria andDetailValueNotEqualTo(String value) {
            addCriterion("detail_value <>", value, "detailValue");
            return (Criteria) this;
        }

        public Criteria andDetailValueGreaterThan(String value) {
            addCriterion("detail_value >", value, "detailValue");
            return (Criteria) this;
        }

        public Criteria andDetailValueGreaterThanOrEqualTo(String value) {
            addCriterion("detail_value >=", value, "detailValue");
            return (Criteria) this;
        }

        public Criteria andDetailValueLessThan(String value) {
            addCriterion("detail_value <", value, "detailValue");
            return (Criteria) this;
        }

        public Criteria andDetailValueLessThanOrEqualTo(String value) {
            addCriterion("detail_value <=", value, "detailValue");
            return (Criteria) this;
        }

        public Criteria andDetailValueLike(String value) {
            addCriterion("detail_value like", value, "detailValue");
            return (Criteria) this;
        }

        public Criteria andDetailValueNotLike(String value) {
            addCriterion("detail_value not like", value, "detailValue");
            return (Criteria) this;
        }

        public Criteria andDetailValueIn(List<String> values) {
            addCriterion("detail_value in", values, "detailValue");
            return (Criteria) this;
        }

        public Criteria andDetailValueNotIn(List<String> values) {
            addCriterion("detail_value not in", values, "detailValue");
            return (Criteria) this;
        }

        public Criteria andDetailValueBetween(String value1, String value2) {
            addCriterion("detail_value between", value1, value2, "detailValue");
            return (Criteria) this;
        }

        public Criteria andDetailValueNotBetween(String value1, String value2) {
            addCriterion("detail_value not between", value1, value2, "detailValue");
            return (Criteria) this;
        }

        public Criteria andDisplayvalueIsNull() {
            addCriterion("displayvalue is null");
            return (Criteria) this;
        }

        public Criteria andDisplayvalueIsNotNull() {
            addCriterion("displayvalue is not null");
            return (Criteria) this;
        }

        public Criteria andDisplayvalueEqualTo(String value) {
            addCriterion("displayvalue =", value, "displayvalue");
            return (Criteria) this;
        }

        public Criteria andDisplayvalueNotEqualTo(String value) {
            addCriterion("displayvalue <>", value, "displayvalue");
            return (Criteria) this;
        }

        public Criteria andDisplayvalueGreaterThan(String value) {
            addCriterion("displayvalue >", value, "displayvalue");
            return (Criteria) this;
        }

        public Criteria andDisplayvalueGreaterThanOrEqualTo(String value) {
            addCriterion("displayvalue >=", value, "displayvalue");
            return (Criteria) this;
        }

        public Criteria andDisplayvalueLessThan(String value) {
            addCriterion("displayvalue <", value, "displayvalue");
            return (Criteria) this;
        }

        public Criteria andDisplayvalueLessThanOrEqualTo(String value) {
            addCriterion("displayvalue <=", value, "displayvalue");
            return (Criteria) this;
        }

        public Criteria andDisplayvalueLike(String value) {
            addCriterion("displayvalue like", value, "displayvalue");
            return (Criteria) this;
        }

        public Criteria andDisplayvalueNotLike(String value) {
            addCriterion("displayvalue not like", value, "displayvalue");
            return (Criteria) this;
        }

        public Criteria andDisplayvalueIn(List<String> values) {
            addCriterion("displayvalue in", values, "displayvalue");
            return (Criteria) this;
        }

        public Criteria andDisplayvalueNotIn(List<String> values) {
            addCriterion("displayvalue not in", values, "displayvalue");
            return (Criteria) this;
        }

        public Criteria andDisplayvalueBetween(String value1, String value2) {
            addCriterion("displayvalue between", value1, value2, "displayvalue");
            return (Criteria) this;
        }

        public Criteria andDisplayvalueNotBetween(String value1, String value2) {
            addCriterion("displayvalue not between", value1, value2, "displayvalue");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andIsusedstateIsNull() {
            addCriterion("isusedstate is null");
            return (Criteria) this;
        }

        public Criteria andIsusedstateIsNotNull() {
            addCriterion("isusedstate is not null");
            return (Criteria) this;
        }

        public Criteria andIsusedstateEqualTo(Short value) {
            addCriterion("isusedstate =", value, "isusedstate");
            return (Criteria) this;
        }

        public Criteria andIsusedstateNotEqualTo(Short value) {
            addCriterion("isusedstate <>", value, "isusedstate");
            return (Criteria) this;
        }

        public Criteria andIsusedstateGreaterThan(Short value) {
            addCriterion("isusedstate >", value, "isusedstate");
            return (Criteria) this;
        }

        public Criteria andIsusedstateGreaterThanOrEqualTo(Short value) {
            addCriterion("isusedstate >=", value, "isusedstate");
            return (Criteria) this;
        }

        public Criteria andIsusedstateLessThan(Short value) {
            addCriterion("isusedstate <", value, "isusedstate");
            return (Criteria) this;
        }

        public Criteria andIsusedstateLessThanOrEqualTo(Short value) {
            addCriterion("isusedstate <=", value, "isusedstate");
            return (Criteria) this;
        }

        public Criteria andIsusedstateIn(List<Short> values) {
            addCriterion("isusedstate in", values, "isusedstate");
            return (Criteria) this;
        }

        public Criteria andIsusedstateNotIn(List<Short> values) {
            addCriterion("isusedstate not in", values, "isusedstate");
            return (Criteria) this;
        }

        public Criteria andIsusedstateBetween(Short value1, Short value2) {
            addCriterion("isusedstate between", value1, value2, "isusedstate");
            return (Criteria) this;
        }

        public Criteria andIsusedstateNotBetween(Short value1, Short value2) {
            addCriterion("isusedstate not between", value1, value2, "isusedstate");
            return (Criteria) this;
        }

        public Criteria andDictDetailParentCodeIsNull() {
            addCriterion("dict_detail_parent_code is null");
            return (Criteria) this;
        }

        public Criteria andDictDetailParentCodeIsNotNull() {
            addCriterion("dict_detail_parent_code is not null");
            return (Criteria) this;
        }

        public Criteria andDictDetailParentCodeEqualTo(String value) {
            addCriterion("dict_detail_parent_code =", value, "dictDetailParentCode");
            return (Criteria) this;
        }

        public Criteria andDictDetailParentCodeNotEqualTo(String value) {
            addCriterion("dict_detail_parent_code <>", value, "dictDetailParentCode");
            return (Criteria) this;
        }

        public Criteria andDictDetailParentCodeGreaterThan(String value) {
            addCriterion("dict_detail_parent_code >", value, "dictDetailParentCode");
            return (Criteria) this;
        }

        public Criteria andDictDetailParentCodeGreaterThanOrEqualTo(String value) {
            addCriterion("dict_detail_parent_code >=", value, "dictDetailParentCode");
            return (Criteria) this;
        }

        public Criteria andDictDetailParentCodeLessThan(String value) {
            addCriterion("dict_detail_parent_code <", value, "dictDetailParentCode");
            return (Criteria) this;
        }

        public Criteria andDictDetailParentCodeLessThanOrEqualTo(String value) {
            addCriterion("dict_detail_parent_code <=", value, "dictDetailParentCode");
            return (Criteria) this;
        }

        public Criteria andDictDetailParentCodeLike(String value) {
            addCriterion("dict_detail_parent_code like", value, "dictDetailParentCode");
            return (Criteria) this;
        }

        public Criteria andDictDetailParentCodeNotLike(String value) {
            addCriterion("dict_detail_parent_code not like", value, "dictDetailParentCode");
            return (Criteria) this;
        }

        public Criteria andDictDetailParentCodeIn(List<String> values) {
            addCriterion("dict_detail_parent_code in", values, "dictDetailParentCode");
            return (Criteria) this;
        }

        public Criteria andDictDetailParentCodeNotIn(List<String> values) {
            addCriterion("dict_detail_parent_code not in", values, "dictDetailParentCode");
            return (Criteria) this;
        }

        public Criteria andDictDetailParentCodeBetween(String value1, String value2) {
            addCriterion("dict_detail_parent_code between", value1, value2, "dictDetailParentCode");
            return (Criteria) this;
        }

        public Criteria andDictDetailParentCodeNotBetween(String value1, String value2) {
            addCriterion("dict_detail_parent_code not between", value1, value2, "dictDetailParentCode");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_dict_detail
     *
     * @mbggenerated do_not_delete_during_merge Wed Sep 12 17:11:40 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_dict_detail
     *
     * @mbggenerated Wed Sep 12 17:11:40 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}