package com.hngd.model;

public class DictDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_dict_detail.id
     *
     * @mbggenerated Wed Sep 12 17:11:40 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_dict_detail.dict_code
     *
     * @mbggenerated Wed Sep 12 17:11:40 CST 2018
     */
    private String dictCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_dict_detail.detail_code
     *
     * @mbggenerated Wed Sep 12 17:11:40 CST 2018
     */
    private String detailCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_dict_detail.detail_value
     *
     * @mbggenerated Wed Sep 12 17:11:40 CST 2018
     */
    private String detailValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_dict_detail.displayvalue
     *
     * @mbggenerated Wed Sep 12 17:11:40 CST 2018
     */
    private String displayvalue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_dict_detail.remark
     *
     * @mbggenerated Wed Sep 12 17:11:40 CST 2018
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_dict_detail.isusedstate
     *
     * @mbggenerated Wed Sep 12 17:11:40 CST 2018
     */
    private Short isusedstate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_dict_detail.dict_detail_parent_code
     *
     * @mbggenerated Wed Sep 12 17:11:40 CST 2018
     */
    private String dictDetailParentCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_dict_detail.id
     *
     * @return the value of tb_dict_detail.id
     *
     * @mbggenerated Wed Sep 12 17:11:40 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_dict_detail.id
     *
     * @param id the value for tb_dict_detail.id
     *
     * @mbggenerated Wed Sep 12 17:11:40 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_dict_detail.dict_code
     *
     * @return the value of tb_dict_detail.dict_code
     *
     * @mbggenerated Wed Sep 12 17:11:40 CST 2018
     */
    public String getDictCode() {
        return dictCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_dict_detail.dict_code
     *
     * @param dictCode the value for tb_dict_detail.dict_code
     *
     * @mbggenerated Wed Sep 12 17:11:40 CST 2018
     */
    public void setDictCode(String dictCode) {
        this.dictCode = dictCode == null ? null : dictCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_dict_detail.detail_code
     *
     * @return the value of tb_dict_detail.detail_code
     *
     * @mbggenerated Wed Sep 12 17:11:40 CST 2018
     */
    public String getDetailCode() {
        return detailCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_dict_detail.detail_code
     *
     * @param detailCode the value for tb_dict_detail.detail_code
     *
     * @mbggenerated Wed Sep 12 17:11:40 CST 2018
     */
    public void setDetailCode(String detailCode) {
        this.detailCode = detailCode == null ? null : detailCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_dict_detail.detail_value
     *
     * @return the value of tb_dict_detail.detail_value
     *
     * @mbggenerated Wed Sep 12 17:11:40 CST 2018
     */
    public String getDetailValue() {
        return detailValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_dict_detail.detail_value
     *
     * @param detailValue the value for tb_dict_detail.detail_value
     *
     * @mbggenerated Wed Sep 12 17:11:40 CST 2018
     */
    public void setDetailValue(String detailValue) {
        this.detailValue = detailValue == null ? null : detailValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_dict_detail.displayvalue
     *
     * @return the value of tb_dict_detail.displayvalue
     *
     * @mbggenerated Wed Sep 12 17:11:40 CST 2018
     */
    public String getDisplayvalue() {
        return displayvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_dict_detail.displayvalue
     *
     * @param displayvalue the value for tb_dict_detail.displayvalue
     *
     * @mbggenerated Wed Sep 12 17:11:40 CST 2018
     */
    public void setDisplayvalue(String displayvalue) {
        this.displayvalue = displayvalue == null ? null : displayvalue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_dict_detail.remark
     *
     * @return the value of tb_dict_detail.remark
     *
     * @mbggenerated Wed Sep 12 17:11:40 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_dict_detail.remark
     *
     * @param remark the value for tb_dict_detail.remark
     *
     * @mbggenerated Wed Sep 12 17:11:40 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_dict_detail.isusedstate
     *
     * @return the value of tb_dict_detail.isusedstate
     *
     * @mbggenerated Wed Sep 12 17:11:40 CST 2018
     */
    public Short getIsusedstate() {
        return isusedstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_dict_detail.isusedstate
     *
     * @param isusedstate the value for tb_dict_detail.isusedstate
     *
     * @mbggenerated Wed Sep 12 17:11:40 CST 2018
     */
    public void setIsusedstate(Short isusedstate) {
        this.isusedstate = isusedstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_dict_detail.dict_detail_parent_code
     *
     * @return the value of tb_dict_detail.dict_detail_parent_code
     *
     * @mbggenerated Wed Sep 12 17:11:40 CST 2018
     */
    public String getDictDetailParentCode() {
        return dictDetailParentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_dict_detail.dict_detail_parent_code
     *
     * @param dictDetailParentCode the value for tb_dict_detail.dict_detail_parent_code
     *
     * @mbggenerated Wed Sep 12 17:11:40 CST 2018
     */
    public void setDictDetailParentCode(String dictDetailParentCode) {
        this.dictDetailParentCode = dictDetailParentCode == null ? null : dictDetailParentCode.trim();
    }
}