package com.hngd.model;

public class Dict {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_dict.id
     *
     * @mbggenerated Wed Sep 12 17:11:40 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_dict.dict_code
     *
     * @mbggenerated Wed Sep 12 17:11:40 CST 2018
     */
    private String dictCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_dict.dict_name
     *
     * @mbggenerated Wed Sep 12 17:11:40 CST 2018
     */
    private String dictName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_dict.flag
     *
     * @mbggenerated Wed Sep 12 17:11:40 CST 2018
     */
    private String flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_dict.remark
     *
     * @mbggenerated Wed Sep 12 17:11:40 CST 2018
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_dict.show_order
     *
     * @mbggenerated Wed Sep 12 17:11:40 CST 2018
     */
    private Integer showOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_dict.third_code
     *
     * @mbggenerated Wed Sep 12 17:11:40 CST 2018
     */
    private String thirdCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_dict.dict_parent_code
     *
     * @mbggenerated Wed Sep 12 17:11:40 CST 2018
     */
    private String dictParentCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_dict.id
     *
     * @return the value of tb_dict.id
     *
     * @mbggenerated Wed Sep 12 17:11:40 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_dict.id
     *
     * @param id the value for tb_dict.id
     *
     * @mbggenerated Wed Sep 12 17:11:40 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_dict.dict_code
     *
     * @return the value of tb_dict.dict_code
     *
     * @mbggenerated Wed Sep 12 17:11:40 CST 2018
     */
    public String getDictCode() {
        return dictCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_dict.dict_code
     *
     * @param dictCode the value for tb_dict.dict_code
     *
     * @mbggenerated Wed Sep 12 17:11:40 CST 2018
     */
    public void setDictCode(String dictCode) {
        this.dictCode = dictCode == null ? null : dictCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_dict.dict_name
     *
     * @return the value of tb_dict.dict_name
     *
     * @mbggenerated Wed Sep 12 17:11:40 CST 2018
     */
    public String getDictName() {
        return dictName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_dict.dict_name
     *
     * @param dictName the value for tb_dict.dict_name
     *
     * @mbggenerated Wed Sep 12 17:11:40 CST 2018
     */
    public void setDictName(String dictName) {
        this.dictName = dictName == null ? null : dictName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_dict.flag
     *
     * @return the value of tb_dict.flag
     *
     * @mbggenerated Wed Sep 12 17:11:40 CST 2018
     */
    public String getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_dict.flag
     *
     * @param flag the value for tb_dict.flag
     *
     * @mbggenerated Wed Sep 12 17:11:40 CST 2018
     */
    public void setFlag(String flag) {
        this.flag = flag == null ? null : flag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_dict.remark
     *
     * @return the value of tb_dict.remark
     *
     * @mbggenerated Wed Sep 12 17:11:40 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_dict.remark
     *
     * @param remark the value for tb_dict.remark
     *
     * @mbggenerated Wed Sep 12 17:11:40 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_dict.show_order
     *
     * @return the value of tb_dict.show_order
     *
     * @mbggenerated Wed Sep 12 17:11:40 CST 2018
     */
    public Integer getShowOrder() {
        return showOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_dict.show_order
     *
     * @param showOrder the value for tb_dict.show_order
     *
     * @mbggenerated Wed Sep 12 17:11:40 CST 2018
     */
    public void setShowOrder(Integer showOrder) {
        this.showOrder = showOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_dict.third_code
     *
     * @return the value of tb_dict.third_code
     *
     * @mbggenerated Wed Sep 12 17:11:40 CST 2018
     */
    public String getThirdCode() {
        return thirdCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_dict.third_code
     *
     * @param thirdCode the value for tb_dict.third_code
     *
     * @mbggenerated Wed Sep 12 17:11:40 CST 2018
     */
    public void setThirdCode(String thirdCode) {
        this.thirdCode = thirdCode == null ? null : thirdCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_dict.dict_parent_code
     *
     * @return the value of tb_dict.dict_parent_code
     *
     * @mbggenerated Wed Sep 12 17:11:40 CST 2018
     */
    public String getDictParentCode() {
        return dictParentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_dict.dict_parent_code
     *
     * @param dictParentCode the value for tb_dict.dict_parent_code
     *
     * @mbggenerated Wed Sep 12 17:11:40 CST 2018
     */
    public void setDictParentCode(String dictParentCode) {
        this.dictParentCode = dictParentCode == null ? null : dictParentCode.trim();
    }
}