package com.hngd.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class PersonnelInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vw_personnel
     *
     * @mbggenerated Thu Sep 06 15:21:50 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vw_personnel
     *
     * @mbggenerated Thu Sep 06 15:21:50 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vw_personnel
     *
     * @mbggenerated Thu Sep 06 15:21:50 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vw_personnel
     *
     * @mbggenerated Thu Sep 06 15:21:50 CST 2018
     */
    public PersonnelInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vw_personnel
     *
     * @mbggenerated Thu Sep 06 15:21:50 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vw_personnel
     *
     * @mbggenerated Thu Sep 06 15:21:50 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vw_personnel
     *
     * @mbggenerated Thu Sep 06 15:21:50 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vw_personnel
     *
     * @mbggenerated Thu Sep 06 15:21:50 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vw_personnel
     *
     * @mbggenerated Thu Sep 06 15:21:50 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vw_personnel
     *
     * @mbggenerated Thu Sep 06 15:21:50 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vw_personnel
     *
     * @mbggenerated Thu Sep 06 15:21:50 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vw_personnel
     *
     * @mbggenerated Thu Sep 06 15:21:50 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vw_personnel
     *
     * @mbggenerated Thu Sep 06 15:21:50 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vw_personnel
     *
     * @mbggenerated Thu Sep 06 15:21:50 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table vw_personnel
     *
     * @mbggenerated Thu Sep 06 15:21:50 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCTime(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Time(value.getTime()), property);
        }

        protected void addCriterionForJDBCTime(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Time> timeList = new ArrayList<java.sql.Time>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                timeList.add(new java.sql.Time(iter.next().getTime()));
            }
            addCriterion(condition, timeList, property);
        }

        protected void addCriterionForJDBCTime(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Time(value1.getTime()), new java.sql.Time(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andPersonnelNumIsNull() {
            addCriterion("personnel_num is null");
            return (Criteria) this;
        }

        public Criteria andPersonnelNumIsNotNull() {
            addCriterion("personnel_num is not null");
            return (Criteria) this;
        }

        public Criteria andPersonnelNumEqualTo(String value) {
            addCriterion("personnel_num =", value, "personnelNum");
            return (Criteria) this;
        }

        public Criteria andPersonnelNumNotEqualTo(String value) {
            addCriterion("personnel_num <>", value, "personnelNum");
            return (Criteria) this;
        }

        public Criteria andPersonnelNumGreaterThan(String value) {
            addCriterion("personnel_num >", value, "personnelNum");
            return (Criteria) this;
        }

        public Criteria andPersonnelNumGreaterThanOrEqualTo(String value) {
            addCriterion("personnel_num >=", value, "personnelNum");
            return (Criteria) this;
        }

        public Criteria andPersonnelNumLessThan(String value) {
            addCriterion("personnel_num <", value, "personnelNum");
            return (Criteria) this;
        }

        public Criteria andPersonnelNumLessThanOrEqualTo(String value) {
            addCriterion("personnel_num <=", value, "personnelNum");
            return (Criteria) this;
        }

        public Criteria andPersonnelNumLike(String value) {
            addCriterion("personnel_num like", value, "personnelNum");
            return (Criteria) this;
        }

        public Criteria andPersonnelNumNotLike(String value) {
            addCriterion("personnel_num not like", value, "personnelNum");
            return (Criteria) this;
        }

        public Criteria andPersonnelNumIn(List<String> values) {
            addCriterion("personnel_num in", values, "personnelNum");
            return (Criteria) this;
        }

        public Criteria andPersonnelNumNotIn(List<String> values) {
            addCriterion("personnel_num not in", values, "personnelNum");
            return (Criteria) this;
        }

        public Criteria andPersonnelNumBetween(String value1, String value2) {
            addCriterion("personnel_num between", value1, value2, "personnelNum");
            return (Criteria) this;
        }

        public Criteria andPersonnelNumNotBetween(String value1, String value2) {
            addCriterion("personnel_num not between", value1, value2, "personnelNum");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andDepNameIsNull() {
            addCriterion("dep_name is null");
            return (Criteria) this;
        }

        public Criteria andDepNameIsNotNull() {
            addCriterion("dep_name is not null");
            return (Criteria) this;
        }

        public Criteria andDepNameEqualTo(String value) {
            addCriterion("dep_name =", value, "depName");
            return (Criteria) this;
        }

        public Criteria andDepNameNotEqualTo(String value) {
            addCriterion("dep_name <>", value, "depName");
            return (Criteria) this;
        }

        public Criteria andDepNameGreaterThan(String value) {
            addCriterion("dep_name >", value, "depName");
            return (Criteria) this;
        }

        public Criteria andDepNameGreaterThanOrEqualTo(String value) {
            addCriterion("dep_name >=", value, "depName");
            return (Criteria) this;
        }

        public Criteria andDepNameLessThan(String value) {
            addCriterion("dep_name <", value, "depName");
            return (Criteria) this;
        }

        public Criteria andDepNameLessThanOrEqualTo(String value) {
            addCriterion("dep_name <=", value, "depName");
            return (Criteria) this;
        }

        public Criteria andDepNameLike(String value) {
            addCriterion("dep_name like", value, "depName");
            return (Criteria) this;
        }

        public Criteria andDepNameNotLike(String value) {
            addCriterion("dep_name not like", value, "depName");
            return (Criteria) this;
        }

        public Criteria andDepNameIn(List<String> values) {
            addCriterion("dep_name in", values, "depName");
            return (Criteria) this;
        }

        public Criteria andDepNameNotIn(List<String> values) {
            addCriterion("dep_name not in", values, "depName");
            return (Criteria) this;
        }

        public Criteria andDepNameBetween(String value1, String value2) {
            addCriterion("dep_name between", value1, value2, "depName");
            return (Criteria) this;
        }

        public Criteria andDepNameNotBetween(String value1, String value2) {
            addCriterion("dep_name not between", value1, value2, "depName");
            return (Criteria) this;
        }

        public Criteria andSexIsNull() {
            addCriterion("sex is null");
            return (Criteria) this;
        }

        public Criteria andSexIsNotNull() {
            addCriterion("sex is not null");
            return (Criteria) this;
        }

        public Criteria andSexEqualTo(Short value) {
            addCriterion("sex =", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotEqualTo(Short value) {
            addCriterion("sex <>", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexGreaterThan(Short value) {
            addCriterion("sex >", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexGreaterThanOrEqualTo(Short value) {
            addCriterion("sex >=", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLessThan(Short value) {
            addCriterion("sex <", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLessThanOrEqualTo(Short value) {
            addCriterion("sex <=", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexIn(List<Short> values) {
            addCriterion("sex in", values, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotIn(List<Short> values) {
            addCriterion("sex not in", values, "sex");
            return (Criteria) this;
        }

        public Criteria andSexBetween(Short value1, Short value2) {
            addCriterion("sex between", value1, value2, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotBetween(Short value1, Short value2) {
            addCriterion("sex not between", value1, value2, "sex");
            return (Criteria) this;
        }

        public Criteria andCardTypeIsNull() {
            addCriterion("card_type is null");
            return (Criteria) this;
        }

        public Criteria andCardTypeIsNotNull() {
            addCriterion("card_type is not null");
            return (Criteria) this;
        }

        public Criteria andCardTypeEqualTo(String value) {
            addCriterion("card_type =", value, "cardType");
            return (Criteria) this;
        }

        public Criteria andCardTypeNotEqualTo(String value) {
            addCriterion("card_type <>", value, "cardType");
            return (Criteria) this;
        }

        public Criteria andCardTypeGreaterThan(String value) {
            addCriterion("card_type >", value, "cardType");
            return (Criteria) this;
        }

        public Criteria andCardTypeGreaterThanOrEqualTo(String value) {
            addCriterion("card_type >=", value, "cardType");
            return (Criteria) this;
        }

        public Criteria andCardTypeLessThan(String value) {
            addCriterion("card_type <", value, "cardType");
            return (Criteria) this;
        }

        public Criteria andCardTypeLessThanOrEqualTo(String value) {
            addCriterion("card_type <=", value, "cardType");
            return (Criteria) this;
        }

        public Criteria andCardTypeLike(String value) {
            addCriterion("card_type like", value, "cardType");
            return (Criteria) this;
        }

        public Criteria andCardTypeNotLike(String value) {
            addCriterion("card_type not like", value, "cardType");
            return (Criteria) this;
        }

        public Criteria andCardTypeIn(List<String> values) {
            addCriterion("card_type in", values, "cardType");
            return (Criteria) this;
        }

        public Criteria andCardTypeNotIn(List<String> values) {
            addCriterion("card_type not in", values, "cardType");
            return (Criteria) this;
        }

        public Criteria andCardTypeBetween(String value1, String value2) {
            addCriterion("card_type between", value1, value2, "cardType");
            return (Criteria) this;
        }

        public Criteria andCardTypeNotBetween(String value1, String value2) {
            addCriterion("card_type not between", value1, value2, "cardType");
            return (Criteria) this;
        }

        public Criteria andPapersNumberIsNull() {
            addCriterion("\"papers_number \" is null");
            return (Criteria) this;
        }

        public Criteria andPapersNumberIsNotNull() {
            addCriterion("\"papers_number \" is not null");
            return (Criteria) this;
        }

        public Criteria andPapersNumberEqualTo(String value) {
            addCriterion("\"papers_number \" =", value, "papersNumber");
            return (Criteria) this;
        }

        public Criteria andPapersNumberNotEqualTo(String value) {
            addCriterion("\"papers_number \" <>", value, "papersNumber");
            return (Criteria) this;
        }

        public Criteria andPapersNumberGreaterThan(String value) {
            addCriterion("\"papers_number \" >", value, "papersNumber");
            return (Criteria) this;
        }

        public Criteria andPapersNumberGreaterThanOrEqualTo(String value) {
            addCriterion("\"papers_number \" >=", value, "papersNumber");
            return (Criteria) this;
        }

        public Criteria andPapersNumberLessThan(String value) {
            addCriterion("\"papers_number \" <", value, "papersNumber");
            return (Criteria) this;
        }

        public Criteria andPapersNumberLessThanOrEqualTo(String value) {
            addCriterion("\"papers_number \" <=", value, "papersNumber");
            return (Criteria) this;
        }

        public Criteria andPapersNumberLike(String value) {
            addCriterion("\"papers_number \" like", value, "papersNumber");
            return (Criteria) this;
        }

        public Criteria andPapersNumberNotLike(String value) {
            addCriterion("\"papers_number \" not like", value, "papersNumber");
            return (Criteria) this;
        }

        public Criteria andPapersNumberIn(List<String> values) {
            addCriterion("\"papers_number \" in", values, "papersNumber");
            return (Criteria) this;
        }

        public Criteria andPapersNumberNotIn(List<String> values) {
            addCriterion("\"papers_number \" not in", values, "papersNumber");
            return (Criteria) this;
        }

        public Criteria andPapersNumberBetween(String value1, String value2) {
            addCriterion("\"papers_number \" between", value1, value2, "papersNumber");
            return (Criteria) this;
        }

        public Criteria andPapersNumberNotBetween(String value1, String value2) {
            addCriterion("\"papers_number \" not between", value1, value2, "papersNumber");
            return (Criteria) this;
        }

        public Criteria andDataBirthIsNull() {
            addCriterion("data_birth is null");
            return (Criteria) this;
        }

        public Criteria andDataBirthIsNotNull() {
            addCriterion("data_birth is not null");
            return (Criteria) this;
        }

        public Criteria andDataBirthEqualTo(Date value) {
            addCriterionForJDBCTime("data_birth =", value, "dataBirth");
            return (Criteria) this;
        }

        public Criteria andDataBirthNotEqualTo(Date value) {
            addCriterionForJDBCTime("data_birth <>", value, "dataBirth");
            return (Criteria) this;
        }

        public Criteria andDataBirthGreaterThan(Date value) {
            addCriterionForJDBCTime("data_birth >", value, "dataBirth");
            return (Criteria) this;
        }

        public Criteria andDataBirthGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCTime("data_birth >=", value, "dataBirth");
            return (Criteria) this;
        }

        public Criteria andDataBirthLessThan(Date value) {
            addCriterionForJDBCTime("data_birth <", value, "dataBirth");
            return (Criteria) this;
        }

        public Criteria andDataBirthLessThanOrEqualTo(Date value) {
            addCriterionForJDBCTime("data_birth <=", value, "dataBirth");
            return (Criteria) this;
        }

        public Criteria andDataBirthIn(List<Date> values) {
            addCriterionForJDBCTime("data_birth in", values, "dataBirth");
            return (Criteria) this;
        }

        public Criteria andDataBirthNotIn(List<Date> values) {
            addCriterionForJDBCTime("data_birth not in", values, "dataBirth");
            return (Criteria) this;
        }

        public Criteria andDataBirthBetween(Date value1, Date value2) {
            addCriterionForJDBCTime("data_birth between", value1, value2, "dataBirth");
            return (Criteria) this;
        }

        public Criteria andDataBirthNotBetween(Date value1, Date value2) {
            addCriterionForJDBCTime("data_birth not between", value1, value2, "dataBirth");
            return (Criteria) this;
        }

        public Criteria andPhoneIsNull() {
            addCriterion("phone is null");
            return (Criteria) this;
        }

        public Criteria andPhoneIsNotNull() {
            addCriterion("phone is not null");
            return (Criteria) this;
        }

        public Criteria andPhoneEqualTo(String value) {
            addCriterion("phone =", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotEqualTo(String value) {
            addCriterion("phone <>", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneGreaterThan(String value) {
            addCriterion("phone >", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("phone >=", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLessThan(String value) {
            addCriterion("phone <", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLessThanOrEqualTo(String value) {
            addCriterion("phone <=", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLike(String value) {
            addCriterion("phone like", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotLike(String value) {
            addCriterion("phone not like", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneIn(List<String> values) {
            addCriterion("phone in", values, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotIn(List<String> values) {
            addCriterion("phone not in", values, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneBetween(String value1, String value2) {
            addCriterion("phone between", value1, value2, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotBetween(String value1, String value2) {
            addCriterion("phone not between", value1, value2, "phone");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table vw_personnel
     *
     * @mbggenerated do_not_delete_during_merge Thu Sep 06 15:21:50 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table vw_personnel
     *
     * @mbggenerated Thu Sep 06 15:21:50 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}