package com.hngd.dao;

import com.hngd.model.DeviceChannel;
import com.hngd.model.DeviceChannelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DeviceChannelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_device_channel
     *
     * @mbggenerated Wed Aug 29 09:54:30 CST 2018
     */
    int countByExample(DeviceChannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_device_channel
     *
     * @mbggenerated Wed Aug 29 09:54:30 CST 2018
     */
    int deleteByExample(DeviceChannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_device_channel
     *
     * @mbggenerated Wed Aug 29 09:54:30 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_device_channel
     *
     * @mbggenerated Wed Aug 29 09:54:30 CST 2018
     */
    int insert(DeviceChannel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_device_channel
     *
     * @mbggenerated Wed Aug 29 09:54:30 CST 2018
     */
    int insertSelective(DeviceChannel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_device_channel
     *
     * @mbggenerated Wed Aug 29 09:54:30 CST 2018
     */
    List<DeviceChannel> selectByExample(DeviceChannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_device_channel
     *
     * @mbggenerated Wed Aug 29 09:54:30 CST 2018
     */
    DeviceChannel selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_device_channel
     *
     * @mbggenerated Wed Aug 29 09:54:30 CST 2018
     */
    int updateByExampleSelective(@Param("record") DeviceChannel record, @Param("example") DeviceChannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_device_channel
     *
     * @mbggenerated Wed Aug 29 09:54:30 CST 2018
     */
    int updateByExample(@Param("record") DeviceChannel record, @Param("example") DeviceChannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_device_channel
     *
     * @mbggenerated Wed Aug 29 09:54:30 CST 2018
     */
    int updateByPrimaryKeySelective(DeviceChannel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_device_channel
     *
     * @mbggenerated Wed Aug 29 09:54:30 CST 2018
     */
    int updateByPrimaryKey(DeviceChannel record);
}