package com.hngd.dao;

import com.hngd.model.DictDetailInfo;
import com.hngd.model.DictDetailInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DictDetailInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vw_dict_detail
     *
     * @mbggenerated Wed Sep 12 17:11:40 CST 2018
     */
    int countByExample(DictDetailInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vw_dict_detail
     *
     * @mbggenerated Wed Sep 12 17:11:40 CST 2018
     */
    int deleteByExample(DictDetailInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vw_dict_detail
     *
     * @mbggenerated Wed Sep 12 17:11:40 CST 2018
     */
    int insert(DictDetailInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vw_dict_detail
     *
     * @mbggenerated Wed Sep 12 17:11:40 CST 2018
     */
    int insertSelective(DictDetailInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vw_dict_detail
     *
     * @mbggenerated Wed Sep 12 17:11:40 CST 2018
     */
    List<DictDetailInfo> selectByExample(DictDetailInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vw_dict_detail
     *
     * @mbggenerated Wed Sep 12 17:11:40 CST 2018
     */
    int updateByExampleSelective(@Param("record") DictDetailInfo record, @Param("example") DictDetailInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vw_dict_detail
     *
     * @mbggenerated Wed Sep 12 17:11:40 CST 2018
     */
    int updateByExample(@Param("record") DictDetailInfo record, @Param("example") DictDetailInfoExample example);
}