package com.hngd.dao;

import com.hngd.model.DictDetail;
import com.hngd.model.DictDetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DictDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dict_detail
     *
     * @mbggenerated Wed Sep 12 17:11:40 CST 2018
     */
    int countByExample(DictDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dict_detail
     *
     * @mbggenerated Wed Sep 12 17:11:40 CST 2018
     */
    int deleteByExample(DictDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dict_detail
     *
     * @mbggenerated Wed Sep 12 17:11:40 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dict_detail
     *
     * @mbggenerated Wed Sep 12 17:11:40 CST 2018
     */
    int insert(DictDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dict_detail
     *
     * @mbggenerated Wed Sep 12 17:11:40 CST 2018
     */
    int insertSelective(DictDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dict_detail
     *
     * @mbggenerated Wed Sep 12 17:11:40 CST 2018
     */
    List<DictDetail> selectByExample(DictDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dict_detail
     *
     * @mbggenerated Wed Sep 12 17:11:40 CST 2018
     */
    DictDetail selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dict_detail
     *
     * @mbggenerated Wed Sep 12 17:11:40 CST 2018
     */
    int updateByExampleSelective(@Param("record") DictDetail record, @Param("example") DictDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dict_detail
     *
     * @mbggenerated Wed Sep 12 17:11:40 CST 2018
     */
    int updateByExample(@Param("record") DictDetail record, @Param("example") DictDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dict_detail
     *
     * @mbggenerated Wed Sep 12 17:11:40 CST 2018
     */
    int updateByPrimaryKeySelective(DictDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dict_detail
     *
     * @mbggenerated Wed Sep 12 17:11:40 CST 2018
     */
    int updateByPrimaryKey(DictDetail record);
}