package com.hngd.dao;

import com.hngd.model.Dict;
import com.hngd.model.DictExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DictMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dict
     *
     * @mbggenerated Wed Sep 12 17:11:40 CST 2018
     */
    int countByExample(DictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dict
     *
     * @mbggenerated Wed Sep 12 17:11:40 CST 2018
     */
    int deleteByExample(DictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dict
     *
     * @mbggenerated Wed Sep 12 17:11:40 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dict
     *
     * @mbggenerated Wed Sep 12 17:11:40 CST 2018
     */
    int insert(Dict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dict
     *
     * @mbggenerated Wed Sep 12 17:11:40 CST 2018
     */
    int insertSelective(Dict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dict
     *
     * @mbggenerated Wed Sep 12 17:11:40 CST 2018
     */
    List<Dict> selectByExample(DictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dict
     *
     * @mbggenerated Wed Sep 12 17:11:40 CST 2018
     */
    Dict selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dict
     *
     * @mbggenerated Wed Sep 12 17:11:40 CST 2018
     */
    int updateByExampleSelective(@Param("record") Dict record, @Param("example") DictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dict
     *
     * @mbggenerated Wed Sep 12 17:11:40 CST 2018
     */
    int updateByExample(@Param("record") Dict record, @Param("example") DictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dict
     *
     * @mbggenerated Wed Sep 12 17:11:40 CST 2018
     */
    int updateByPrimaryKeySelective(Dict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dict
     *
     * @mbggenerated Wed Sep 12 17:11:40 CST 2018
     */
    int updateByPrimaryKey(Dict record);
}