package com.hngd.dao;

import com.hngd.model.DomainOrgExample;
import com.hngd.model.DomainOrgKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DomainOrgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_domain_org
     *
     * @mbggenerated Wed Aug 29 09:54:30 CST 2018
     */
    int countByExample(DomainOrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_domain_org
     *
     * @mbggenerated Wed Aug 29 09:54:30 CST 2018
     */
    int deleteByExample(DomainOrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_domain_org
     *
     * @mbggenerated Wed Aug 29 09:54:30 CST 2018
     */
    int deleteByPrimaryKey(DomainOrgKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_domain_org
     *
     * @mbggenerated Wed Aug 29 09:54:30 CST 2018
     */
    int insert(DomainOrgKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_domain_org
     *
     * @mbggenerated Wed Aug 29 09:54:30 CST 2018
     */
    int insertSelective(DomainOrgKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_domain_org
     *
     * @mbggenerated Wed Aug 29 09:54:30 CST 2018
     */
    List<DomainOrgKey> selectByExample(DomainOrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_domain_org
     *
     * @mbggenerated Wed Aug 29 09:54:30 CST 2018
     */
    int updateByExampleSelective(@Param("record") DomainOrgKey record, @Param("example") DomainOrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_domain_org
     *
     * @mbggenerated Wed Aug 29 09:54:30 CST 2018
     */
    int updateByExample(@Param("record") DomainOrgKey record, @Param("example") DomainOrgExample example);
}