package com.hngd.dao;

import com.hngd.model.PersonnelInfo;
import com.hngd.model.PersonnelInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PersonnelInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vw_personnel
     *
     * @mbggenerated Thu Sep 06 15:21:50 CST 2018
     */
    int countByExample(PersonnelInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vw_personnel
     *
     * @mbggenerated Thu Sep 06 15:21:50 CST 2018
     */
    int deleteByExample(PersonnelInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vw_personnel
     *
     * @mbggenerated Thu Sep 06 15:21:50 CST 2018
     */
    int insert(PersonnelInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vw_personnel
     *
     * @mbggenerated Thu Sep 06 15:21:50 CST 2018
     */
    int insertSelective(PersonnelInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vw_personnel
     *
     * @mbggenerated Thu Sep 06 15:21:50 CST 2018
     */
    List<PersonnelInfo> selectByExample(PersonnelInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vw_personnel
     *
     * @mbggenerated Thu Sep 06 15:21:50 CST 2018
     */
    int updateByExampleSelective(@Param("record") PersonnelInfo record, @Param("example") PersonnelInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vw_personnel
     *
     * @mbggenerated Thu Sep 06 15:21:50 CST 2018
     */
    int updateByExample(@Param("record") PersonnelInfo record, @Param("example") PersonnelInfoExample example);
}