package com.hngd.dao;

import com.hngd.model.Personnel;
import com.hngd.model.PersonnelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PersonnelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_personnel
     *
     * @mbggenerated Thu Sep 06 14:49:39 CST 2018
     */
    int countByExample(PersonnelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_personnel
     *
     * @mbggenerated Thu Sep 06 14:49:39 CST 2018
     */
    int deleteByExample(PersonnelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_personnel
     *
     * @mbggenerated Thu Sep 06 14:49:39 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_personnel
     *
     * @mbggenerated Thu Sep 06 14:49:39 CST 2018
     */
    int insert(Personnel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_personnel
     *
     * @mbggenerated Thu Sep 06 14:49:39 CST 2018
     */
    int insertSelective(Personnel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_personnel
     *
     * @mbggenerated Thu Sep 06 14:49:39 CST 2018
     */
    List<Personnel> selectByExample(PersonnelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_personnel
     *
     * @mbggenerated Thu Sep 06 14:49:39 CST 2018
     */
    Personnel selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_personnel
     *
     * @mbggenerated Thu Sep 06 14:49:39 CST 2018
     */
    int updateByExampleSelective(@Param("record") Personnel record, @Param("example") PersonnelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_personnel
     *
     * @mbggenerated Thu Sep 06 14:49:39 CST 2018
     */
    int updateByExample(@Param("record") Personnel record, @Param("example") PersonnelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_personnel
     *
     * @mbggenerated Thu Sep 06 14:49:39 CST 2018
     */
    int updateByPrimaryKeySelective(Personnel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_personnel
     *
     * @mbggenerated Thu Sep 06 14:49:39 CST 2018
     */
    int updateByPrimaryKey(Personnel record);
}